export const {
  REACT_APP_SENTRY_DSN: SENTRY_DSN,
  REACT_APP_BASE_URL: API_BASE,
  REACT_APP_CLIENT_ID: CLIENT_ID,
  REACT_APP_USER_POOL_ID: USER_POOL_ID,
  REACT_APP_REGION: REGION,
} = process.env;
